"""
Catalogo esteso: categorie e prodotti aggiuntivi rispetto al catalogo base di server.py.

Ogni prodotto: (id, nome, categoria, quantità di riferimento, unità, prezzo di stima in €
per quella quantità, baseline Conad). I prezzi sono STIME: vengono sostituiti dai prezzi
reali quando una fonte li ha. Gli id non vanno mai cambiati (sono nello storico e nelle liste).
"""

NEW_CATEGORIES = [
    {"id": "salumi", "name": "Salumi e formaggi", "emoji": "🥓"},
    {"id": "colazione", "name": "Colazione", "emoji": "☕"},
    {"id": "dolci", "name": "Dolci e snack", "emoji": "🍫"},
    {"id": "condimenti", "name": "Condimenti e salse", "emoji": "🫒"},
    {"id": "gastronomia", "name": "Pronti e gastronomia", "emoji": "🥪"},
    {"id": "persona", "name": "Cura della persona", "emoji": "🧼"},
    {"id": "bambini", "name": "Bambini", "emoji": "🍼"},
    {"id": "animali", "name": "Animali", "emoji": "🐾"},
    {"id": "altro", "name": "Altro", "emoji": "🛒"},  # prodotti scritti a mano non riconosciuti
]

EXTRA_PRODUCTS = [
    # --- Frutta ---
    ("mele_rosse", "Mele Red Delicious", "frutta", 1, "kg", 2.39),
    ("mele_verdi", "Mele Granny Smith", "frutta", 1, "kg", 2.49),
    ("limoni", "Limoni", "frutta", 0.5, "kg", 1.29),
    ("mandarini", "Mandarini / clementine", "frutta", 1, "kg", 2.19),
    ("kiwi", "Kiwi", "frutta", 1, "kg", 2.79),
    ("uva_bianca", "Uva bianca", "frutta", 1, "kg", 2.99),
    ("uva_nera", "Uva nera", "frutta", 1, "kg", 3.19),
    ("pesche", "Pesche", "frutta", 1, "kg", 2.69),
    ("albicocche", "Albicocche", "frutta", 1, "kg", 3.49),
    ("ciliegie", "Ciliegie", "frutta", 0.5, "kg", 4.49),
    ("anguria", "Anguria", "frutta", 3, "kg", 2.70),
    ("melone", "Melone", "frutta", 1.5, "kg", 2.99),
    ("ananas", "Ananas", "frutta", 1, "pz", 1.99),
    ("avocado", "Avocado", "frutta", 2, "pz", 2.49),
    ("frutti_bosco", "Frutti di bosco", "frutta", 0.125, "kg", 2.29),
    ("mirtilli", "Mirtilli", "frutta", 0.125, "kg", 2.49),
    ("pompelmi", "Pompelmi", "frutta", 1, "kg", 2.29),
    ("prugne", "Prugne", "frutta", 1, "kg", 2.79),
    ("fichi", "Fichi", "frutta", 0.5, "kg", 3.29),
    ("cachi", "Cachi", "frutta", 1, "kg", 2.59),
    ("frutta_secca_mix", "Frutta secca mista 200g", "frutta", 1, "conf", 3.49),
    ("noci", "Noci sgusciate 200g", "frutta", 1, "conf", 3.29),
    ("mandorle", "Mandorle 200g", "frutta", 1, "conf", 3.49),
    # --- Verdura ---
    ("pomodorini", "Pomodorini ciliegino 500g", "verdura", 1, "conf", 1.89),
    ("melanzane", "Melanzane", "verdura", 1, "kg", 2.29),
    ("peperoni", "Peperoni", "verdura", 1, "kg", 2.99),
    ("cetrioli", "Cetrioli", "verdura", 1, "kg", 1.99),
    ("lattuga", "Lattuga", "verdura", 1, "pz", 1.09),
    ("rucola", "Rucola 125g", "verdura", 1, "conf", 1.49),
    ("spinaci", "Spinaci freschi 500g", "verdura", 1, "conf", 2.29),
    ("insalata_busta", "Insalata in busta 200g", "verdura", 1, "conf", 1.59),
    ("broccoli", "Broccoli", "verdura", 1, "kg", 2.49),
    ("cavolfiore", "Cavolfiore", "verdura", 1, "pz", 1.99),
    ("finocchi", "Finocchi", "verdura", 1, "kg", 1.89),
    ("sedano", "Sedano", "verdura", 1, "pz", 1.29),
    ("aglio", "Aglio", "verdura", 0.25, "kg", 1.49),
    ("cipolle_rosse", "Cipolle rosse di Tropea", "verdura", 0.5, "kg", 1.79),
    ("porri", "Porri", "verdura", 0.5, "kg", 1.69),
    ("funghi", "Funghi champignon 400g", "verdura", 1, "conf", 2.19),
    ("zucca", "Zucca", "verdura", 1, "kg", 1.69),
    ("carciofi", "Carciofi", "verdura", 4, "pz", 3.49),
    ("asparagi", "Asparagi", "verdura", 0.5, "kg", 3.99),
    ("fagiolini", "Fagiolini", "verdura", 0.5, "kg", 2.29),
    ("patate_dolci", "Patate dolci", "verdura", 1, "kg", 2.99),
    ("basilico", "Basilico fresco", "verdura", 1, "pz", 1.29),
    ("prezzemolo", "Prezzemolo", "verdura", 1, "pz", 0.89),
    ("minestrone_fresco", "Minestrone fresco 1kg", "verdura", 1, "conf", 2.99),
    # --- Carne ---
    ("cosce_pollo", "Cosce di pollo", "carne", 1, "kg", 4.99),
    ("ali_pollo", "Ali di pollo", "carne", 1, "kg", 4.49),
    ("pollo_intero", "Pollo intero", "carne", 1.5, "kg", 6.90),
    ("fesa_tacchino", "Fesa di tacchino a fette", "carne", 0.4, "kg", 5.49),
    ("hamburger", "Hamburger di manzo x2", "carne", 1, "conf", 3.99),
    ("spezzatino", "Spezzatino di manzo", "carne", 0.5, "kg", 6.49),
    ("fettine_manzo", "Fettine di manzo", "carne", 0.4, "kg", 6.29),
    ("arrosto_maiale", "Arista di maiale", "carne", 0.8, "kg", 6.80),
    ("braciole_maiale", "Braciole di maiale", "carne", 0.6, "kg", 5.49),
    ("costine", "Costine di maiale", "carne", 1, "kg", 6.99),
    ("vitello_fettine", "Fettine di vitello", "carne", 0.3, "kg", 6.90),
    ("agnello", "Agnello", "carne", 0.8, "kg", 11.90),
    ("wurstel", "Würstel 250g", "carne", 1, "conf", 1.99),
    ("cotolette_pollo", "Cotolette di pollo panate", "carne", 1, "conf", 3.69),
    ("polpette", "Polpette di carne pronte da cuocere", "carne", 1, "conf", 3.99),
    # --- Pesce ---
    ("orata", "Orata fresca", "pesce", 0.4, "kg", 6.40),
    ("branzino", "Branzino fresco", "pesce", 0.4, "kg", 6.80),
    ("gamberi", "Gamberi", "pesce", 0.3, "kg", 6.99),
    ("cozze", "Cozze", "pesce", 1, "kg", 3.99),
    ("vongole", "Vongole", "pesce", 0.5, "kg", 5.99),
    ("calamari", "Calamari", "pesce", 0.5, "kg", 7.49),
    ("polpo", "Polpo", "pesce", 0.8, "kg", 11.90),
    ("salmone_affumicato", "Salmone affumicato 100g", "pesce", 1, "conf", 3.99),
    ("sgombro_scatola", "Sgombro in scatola", "pesce", 1, "pz", 2.29),
    ("alici", "Filetti di alici sott'olio", "pesce", 1, "pz", 2.79),
    ("bastoncini_pesce", "Bastoncini di pesce surgelati", "pesce", 1, "conf", 3.49),
    ("tonno_vetro", "Tonno in vetro 200g", "pesce", 1, "pz", 4.29),
    # --- Latticini e uova ---
    ("latte_scremato", "Latte parzialmente scremato 1L", "latticini", 1, "L", 1.45),
    ("latte_lungaconservazione", "Latte UHT 1L", "latticini", 1, "L", 1.19),
    ("latte_senza_lattosio", "Latte senza lattosio 1L", "latticini", 1, "L", 1.79),
    ("bevanda_soia", "Bevanda di soia 1L", "latticini", 1, "L", 1.69),
    ("bevanda_avena", "Bevanda d'avena 1L", "latticini", 1, "L", 1.79),
    ("uova_x10", "Uova fresche x10", "latticini", 1, "conf", 3.29),
    ("panna", "Panna da cucina 200ml", "latticini", 1, "pz", 1.09),
    ("panna_montare", "Panna da montare 250ml", "latticini", 1, "pz", 1.69),
    ("yogurt_greco", "Yogurt greco 500g", "latticini", 1, "pz", 2.49),
    ("yogurt_frutta", "Yogurt alla frutta 2x125g", "latticini", 1, "conf", 1.19),
    ("kefir", "Kefir 480g", "latticini", 1, "pz", 1.99),
    ("mascarpone", "Mascarpone 250g", "latticini", 1, "pz", 2.29),
    ("burrata", "Burrata 125g", "latticini", 1, "pz", 2.49),
    ("mozzarella_bufala", "Mozzarella di bufala 250g", "latticini", 1, "pz", 3.99),
    ("fiordilatte", "Fiordilatte per pizza 400g", "latticini", 1, "pz", 2.99),
    ("budino", "Budino al cioccolato x4", "latticini", 1, "conf", 1.99),
    # --- Salumi e formaggi ---
    ("prosciutto_crudo", "Prosciutto crudo a fette", "salumi", 0.1, "kg", 3.49),
    ("salame", "Salame a fette", "salumi", 0.1, "kg", 2.49),
    ("mortadella", "Mortadella a fette", "salumi", 0.15, "kg", 2.29),
    ("bresaola", "Bresaola a fette", "salumi", 0.08, "kg", 3.99),
    ("speck", "Speck a fette", "salumi", 0.1, "kg", 2.99),
    ("pancetta", "Pancetta a cubetti", "salumi", 0.15, "kg", 2.29),
    ("tacchino_fette", "Petto di tacchino arrosto a fette", "salumi", 0.1, "kg", 2.49),
    ("grana_padano", "Grana Padano", "salumi", 0.3, "kg", 5.49),
    ("grana_grattugiato", "Formaggio grattugiato 100g", "salumi", 1, "pz", 2.29),
    ("pecorino", "Pecorino Romano", "salumi", 0.2, "kg", 4.49),
    ("gorgonzola", "Gorgonzola", "salumi", 0.2, "kg", 2.99),
    ("provolone", "Provolone", "salumi", 0.25, "kg", 3.29),
    ("ricotta", "Ricotta 250g", "salumi", 1, "pz", 1.69),
    ("stracchino", "Stracchino 200g", "salumi", 1, "pz", 1.99),
    ("sottilette", "Formaggio a fette x10", "salumi", 1, "conf", 1.89),
    ("asiago", "Asiago", "salumi", 0.25, "kg", 3.49),
    ("feta", "Feta 200g", "salumi", 1, "pz", 2.49),
    ("emmental", "Emmental a fette", "salumi", 0.15, "kg", 2.29),
    ("formaggio_spalmabile", "Formaggio spalmabile 150g", "salumi", 1, "pz", 1.79),
    # --- Pane e forno ---
    ("pancarre", "Pan carrè", "pane", 1, "conf", 1.79),
    ("pane_integrale", "Pane integrale", "pane", 0.5, "kg", 2.49),
    ("baguette", "Baguette", "pane", 1, "pz", 0.99),
    ("piadina", "Piadine x4", "pane", 1, "conf", 1.99),
    ("tortillas", "Tortillas x6", "pane", 1, "conf", 1.99),
    ("grissini", "Grissini", "pane", 1, "conf", 1.49),
    ("taralli", "Taralli", "pane", 1, "conf", 1.79),
    ("gallette_riso", "Gallette di riso", "pane", 1, "conf", 1.29),
    ("pangrattato", "Pangrattato", "pane", 1, "conf", 0.99),
    ("focaccia", "Focaccia", "pane", 1, "pz", 2.49),
    ("pizza_base", "Base per pizza", "pane", 1, "conf", 1.99),
    ("pasta_sfoglia", "Pasta sfoglia rotonda", "pane", 1, "pz", 1.49),
    ("pasta_brisee", "Pasta brisée", "pane", 1, "pz", 1.49),
    ("croissant", "Croissant x6", "pane", 1, "conf", 2.49),
    # --- Colazione ---
    ("cereali", "Cereali corn flakes", "colazione", 1, "conf", 2.49),
    ("muesli", "Muesli", "colazione", 1, "conf", 2.99),
    ("fiocchi_avena", "Fiocchi d'avena 500g", "colazione", 1, "conf", 1.49),
    ("caffe_capsule", "Caffè in capsule x10", "colazione", 1, "conf", 3.49),
    ("caffe_grani", "Caffè in grani 1kg", "colazione", 1, "conf", 14.90),
    ("caffe_solubile", "Caffè solubile", "colazione", 1, "pz", 4.49),
    ("orzo", "Orzo solubile", "colazione", 1, "pz", 2.99),
    ("te", "Tè nero x25", "colazione", 1, "conf", 1.79),
    ("tisana", "Tisana / camomilla x20", "colazione", 1, "conf", 1.99),
    ("cacao", "Cacao amaro", "colazione", 1, "pz", 2.49),
    ("marmellata", "Marmellata / confettura", "colazione", 1, "pz", 2.29),
    ("miele", "Miele", "colazione", 1, "pz", 4.49),
    ("crema_nocciole", "Crema spalmabile alle nocciole 400g", "colazione", 1, "pz", 3.99),
    ("merendine", "Merendine x10", "colazione", 1, "conf", 2.69),
    ("plumcake", "Plumcake x10", "colazione", 1, "conf", 2.49),
    ("biscotti_integrali", "Biscotti integrali", "colazione", 1, "conf", 2.49),
    ("zucchero_canna", "Zucchero di canna", "colazione", 1, "kg", 2.29),
    ("dolcificante", "Dolcificante", "colazione", 1, "pz", 2.49),
    # --- Dispensa ---
    ("spaghetti", "Spaghetti 500g", "dispensa", 1, "pz", 0.99),
    ("penne", "Penne rigate 500g", "dispensa", 1, "pz", 0.99),
    ("fusilli", "Fusilli 500g", "dispensa", 1, "pz", 0.99),
    ("pasta_integrale", "Pasta integrale 500g", "dispensa", 1, "pz", 1.29),
    ("pasta_uovo", "Pasta all'uovo 250g", "dispensa", 1, "pz", 1.79),
    ("lasagne_secche", "Sfoglie per lasagne", "dispensa", 1, "pz", 1.69),
    ("gnocchi", "Gnocchi di patate 500g", "dispensa", 1, "pz", 1.49),
    ("tortellini", "Tortellini freschi 250g", "dispensa", 1, "pz", 2.49),
    ("riso_basmati", "Riso basmati 1kg", "dispensa", 1, "kg", 2.99),
    ("riso_arborio", "Riso Arborio 1kg", "dispensa", 1, "kg", 2.69),
    ("cous_cous", "Cous cous 500g", "dispensa", 1, "pz", 1.69),
    ("farro", "Farro 500g", "dispensa", 1, "pz", 1.99),
    ("orzo_perlato", "Orzo perlato 500g", "dispensa", 1, "pz", 1.49),
    ("polenta", "Farina per polenta 1kg", "dispensa", 1, "kg", 1.59),
    ("lenticchie", "Lenticchie secche 500g", "dispensa", 1, "pz", 1.89),
    ("fagioli_scatola", "Fagioli borlotti in scatola", "dispensa", 1, "pz", 0.89),
    ("piselli_scatola", "Piselli in scatola", "dispensa", 1, "pz", 0.99),
    ("mais_scatola", "Mais dolce in scatola", "dispensa", 1, "pz", 0.99),
    ("pelati", "Pomodori pelati 400g", "dispensa", 1, "pz", 0.79),
    ("polpa_pomodoro", "Polpa di pomodoro 400g", "dispensa", 1, "pz", 0.79),
    ("concentrato", "Concentrato di pomodoro", "dispensa", 1, "pz", 0.99),
    ("sugo_pronto", "Sugo pronto al basilico", "dispensa", 1, "pz", 1.99),
    ("pesto", "Pesto alla genovese", "dispensa", 1, "pz", 2.49),
    ("ragu", "Ragù pronto", "dispensa", 1, "pz", 2.29),
    ("dado", "Dado da brodo", "dispensa", 1, "conf", 1.29),
    ("brodo_pronto", "Brodo pronto 1L", "dispensa", 1, "pz", 1.79),
    ("lievito", "Lievito per dolci", "dispensa", 1, "conf", 0.99),
    ("lievito_birra", "Lievito di birra", "dispensa", 1, "pz", 0.49),
    ("farina_manitoba", "Farina Manitoba 1kg", "dispensa", 1, "kg", 1.59),
    ("fecola", "Fecola di patate", "dispensa", 1, "pz", 1.29),
    ("cioccolato_cucina", "Cioccolato fondente da cucina", "dispensa", 1, "pz", 1.99),
    ("olive", "Olive verdi / nere", "dispensa", 1, "pz", 1.99),
    ("capperi", "Capperi", "dispensa", 1, "pz", 1.79),
    ("sottaceti", "Sottaceti misti", "dispensa", 1, "pz", 1.99),
    ("funghi_trifolati", "Funghi trifolati", "dispensa", 1, "pz", 2.29),
    ("carciofini", "Carciofini sott'olio", "dispensa", 1, "pz", 2.99),
    ("zuppa_pronta", "Zuppa pronta", "dispensa", 1, "pz", 2.49),
    ("pure_patate", "Purè di patate in fiocchi", "dispensa", 1, "conf", 1.79),
    # --- Condimenti e salse ---
    ("olio_semi", "Olio di semi 1L", "condimenti", 1, "L", 2.49),
    ("olio_oliva", "Olio di oliva 1L", "condimenti", 1, "L", 7.49),
    ("aceto_vino", "Aceto di vino", "condimenti", 1, "pz", 0.99),
    ("aceto_balsamico", "Aceto balsamico di Modena", "condimenti", 1, "pz", 2.49),
    ("sale_fino", "Sale fino 1kg", "condimenti", 1, "kg", 0.49),
    ("sale_grosso", "Sale grosso 1kg", "condimenti", 1, "kg", 0.45),
    ("pepe", "Pepe nero macinato", "condimenti", 1, "pz", 1.99),
    ("origano", "Origano", "condimenti", 1, "pz", 1.29),
    ("spezie_mix", "Spezie miste", "condimenti", 1, "pz", 1.79),
    ("maionese", "Maionese", "condimenti", 1, "pz", 1.99),
    ("ketchup", "Ketchup", "condimenti", 1, "pz", 1.89),
    ("senape", "Senape", "condimenti", 1, "pz", 1.49),
    ("salsa_soia", "Salsa di soia", "condimenti", 1, "pz", 2.29),
    ("tonnato", "Salsa tonnata", "condimenti", 1, "pz", 2.49),
    ("burro_arachidi", "Burro di arachidi", "condimenti", 1, "pz", 2.99),
    # --- Dolci e snack ---
    ("cioccolato_latte", "Tavoletta cioccolato al latte", "dolci", 1, "pz", 1.49),
    ("cioccolato_fondente", "Tavoletta cioccolato fondente", "dolci", 1, "pz", 1.69),
    ("patatine", "Patatine classiche", "dolci", 1, "conf", 1.79),
    ("snack_mais", "Snack di mais", "dolci", 1, "conf", 1.49),
    ("arachidi", "Arachidi salate", "dolci", 1, "conf", 1.69),
    ("pop_corn", "Pop corn da microonde", "dolci", 1, "conf", 1.99),
    ("caramelle", "Caramelle", "dolci", 1, "conf", 1.49),
    ("chewing_gum", "Gomme da masticare", "dolci", 1, "conf", 1.29),
    ("wafer", "Wafer", "dolci", 1, "conf", 1.69),
    ("barrette", "Barrette ai cereali x6", "dolci", 1, "conf", 2.29),
    ("torta_pronta", "Torta / crostata pronta", "dolci", 1, "pz", 3.49),
    ("crackers_integrali", "Crackers integrali", "dolci", 1, "conf", 1.79),
    # --- Bevande ---
    ("acqua_frizzante", "Acqua frizzante 6x1,5L", "bevande", 1, "conf", 2.29),
    ("acqua_piccola", "Acqua naturale 6x0,5L", "bevande", 1, "conf", 1.99),
    ("cola", "Cola 1,5L", "bevande", 1, "pz", 1.79),
    ("aranciata", "Aranciata 1,5L", "bevande", 1, "pz", 1.59),
    ("te_freddo", "Tè freddo 1,5L", "bevande", 1, "pz", 1.49),
    ("succo_ace", "Succo ACE 1L", "bevande", 1, "L", 1.49),
    ("spremuta", "Spremuta d'arancia 1L", "bevande", 1, "L", 2.99),
    ("vino_bianco", "Vino bianco 75cl", "bevande", 1, "pz", 4.99),
    ("prosecco", "Prosecco 75cl", "bevande", 1, "pz", 6.49),
    ("birra_bottiglia", "Birra 66cl", "bevande", 1, "pz", 1.29),
    ("birra_analcolica", "Birra analcolica 3x33cl", "bevande", 1, "conf", 2.99),
    ("bevanda_sport", "Bevanda energetica / isotonica", "bevande", 1, "pz", 1.49),
    ("sciroppo", "Sciroppo / succo concentrato", "bevande", 1, "pz", 2.49),
    # --- Surgelati ---
    ("spinaci_surg", "Spinaci surgelati 1kg", "surgelati", 1, "conf", 2.49),
    ("minestrone_surg", "Minestrone surgelato 1kg", "surgelati", 1, "conf", 2.49),
    ("verdure_grigliate", "Verdure grigliate surgelate", "surgelati", 1, "conf", 2.99),
    ("patatine_forno", "Patatine fritte surgelate 1kg", "surgelati", 1, "conf", 2.49),
    ("fagiolini_surg", "Fagiolini surgelati 1kg", "surgelati", 1, "conf", 2.29),
    ("gamberetti_surg", "Gamberetti surgelati", "surgelati", 1, "conf", 4.99),
    ("misto_mare", "Misto mare surgelato", "surgelati", 1, "conf", 5.49),
    ("filetti_merluzzo_surg", "Filetti di merluzzo surgelati", "surgelati", 1, "conf", 4.99),
    ("pasta_surg", "Primo piatto surgelato", "surgelati", 1, "conf", 3.49),
    ("lasagne_surg", "Lasagne surgelate", "surgelati", 1, "conf", 3.99),
    ("cornetti_surg", "Cornetti surgelati x6", "surgelati", 1, "conf", 2.99),
    ("ghiaccioli", "Ghiaccioli x8", "surgelati", 1, "conf", 2.49),
    ("coni_gelato", "Coni gelato x6", "surgelati", 1, "conf", 3.49),
    # --- Pronti e gastronomia ---
    ("insalata_pronta", "Insalatona pronta", "gastronomia", 1, "pz", 3.49),
    ("lasagna_pronta", "Lasagna pronta da scaldare", "gastronomia", 1, "pz", 4.49),
    ("pizza_fresca", "Pizza fresca da banco frigo", "gastronomia", 1, "pz", 2.99),
    ("piadina_farcita", "Piadina farcita", "gastronomia", 1, "pz", 2.99),
    ("tramezzini", "Tramezzini x2", "gastronomia", 1, "conf", 2.49),
    ("hummus", "Hummus", "gastronomia", 1, "pz", 2.29),
    ("pollo_arrosto", "Pollo arrosto", "gastronomia", 1, "pz", 6.99),
    ("burger_vegetale", "Burger vegetale x2", "gastronomia", 1, "conf", 2.99),
    ("tofu", "Tofu", "gastronomia", 1, "pz", 2.29),
    # --- Casa ---
    ("ammorbidente", "Ammorbidente", "casa", 1, "pz", 2.99),
    ("candeggina", "Candeggina", "casa", 1, "pz", 1.29),
    ("sgrassatore", "Sgrassatore spray", "casa", 1, "pz", 2.49),
    ("detersivo_pavimenti", "Detersivo pavimenti", "casa", 1, "pz", 2.29),
    ("vetri", "Detergente vetri", "casa", 1, "pz", 1.99),
    ("anticalcare", "Anticalcare bagno", "casa", 1, "pz", 2.49),
    ("pastiglie_lavastoviglie", "Pastiglie lavastoviglie x30", "casa", 1, "conf", 5.99),
    ("sale_lavastoviglie", "Sale per lavastoviglie", "casa", 1, "pz", 1.49),
    ("brillantante", "Brillantante lavastoviglie", "casa", 1, "pz", 2.49),
    ("carta_cucina", "Carta da cucina x4", "casa", 1, "conf", 2.99),
    ("fazzoletti", "Fazzoletti di carta x10", "casa", 1, "conf", 1.99),
    ("tovaglioli", "Tovaglioli di carta", "casa", 1, "conf", 1.49),
    ("sacchi_spazzatura", "Sacchi spazzatura", "casa", 1, "conf", 1.99),
    ("sacchetti_gelo", "Sacchetti gelo", "casa", 1, "conf", 1.49),
    ("pellicola", "Pellicola trasparente", "casa", 1, "pz", 1.49),
    ("alluminio", "Carta alluminio", "casa", 1, "pz", 1.79),
    ("carta_forno", "Carta forno", "casa", 1, "pz", 1.69),
    ("spugne", "Spugne x3", "casa", 1, "conf", 1.29),
    ("guanti", "Guanti in lattice", "casa", 1, "conf", 1.99),
    ("pile", "Pile stilo AA x4", "casa", 1, "conf", 3.99),
    ("lampadina", "Lampadina LED", "casa", 1, "pz", 2.99),
    # --- Cura della persona ---
    ("bagnoschiuma", "Bagnoschiuma", "persona", 1, "pz", 2.49),
    ("sapone_mani", "Sapone liquido mani", "persona", 1, "pz", 1.49),
    ("balsamo", "Balsamo capelli", "persona", 1, "pz", 2.99),
    ("dentifricio", "Dentifricio", "persona", 1, "pz", 1.99),
    ("spazzolino", "Spazzolino", "persona", 1, "pz", 1.79),
    ("collutorio", "Collutorio", "persona", 1, "pz", 2.99),
    ("deodorante", "Deodorante", "persona", 1, "pz", 2.79),
    ("rasoi", "Rasoi usa e getta", "persona", 1, "conf", 3.49),
    ("schiuma_barba", "Schiuma da barba", "persona", 1, "pz", 2.49),
    ("assorbenti", "Assorbenti", "persona", 1, "conf", 2.99),
    ("cotton_fioc", "Cotton fioc", "persona", 1, "conf", 1.29),
    ("dischetti", "Dischetti struccanti", "persona", 1, "conf", 1.49),
    ("crema_corpo", "Crema corpo", "persona", 1, "pz", 3.49),
    ("salviette", "Salviette umidificate", "persona", 1, "conf", 1.49),
    ("cerotti", "Cerotti", "persona", 1, "conf", 2.49),
    # --- Bambini ---
    ("pannolini", "Pannolini", "bambini", 1, "conf", 9.99),
    ("salviette_bimbi", "Salviette per bambini", "bambini", 1, "conf", 1.99),
    ("omogeneizzati", "Omogeneizzati x2", "bambini", 1, "conf", 1.99),
    ("latte_crescita", "Latte di crescita 1L", "bambini", 1, "L", 2.49),
    ("biscotti_bimbi", "Biscotti per l'infanzia", "bambini", 1, "conf", 2.99),
    ("succo_bimbi", "Succhi di frutta piccoli x3", "bambini", 1, "conf", 1.49),
    # --- Animali ---
    ("crocchette_cane", "Crocchette per cani", "animali", 1, "conf", 4.99),
    ("umido_cane", "Cibo umido per cani", "animali", 1, "pz", 1.29),
    ("crocchette_gatto", "Crocchette per gatti", "animali", 1, "conf", 4.49),
    ("umido_gatto", "Bustine per gatti x4", "animali", 1, "conf", 2.49),
    ("lettiera", "Lettiera per gatti", "animali", 1, "conf", 4.99),
    ("snack_animali", "Snack per animali", "animali", 1, "conf", 2.29),
]
